clear;
clc;

scene = mMitsubaElement.scene();

sphere = mMitsubaElement('mySphere', 'shape', 'sphere');
scene.append(sphere);

radius = mMitsubaProperty.withValue('radius', 'float', 10);
sphere.append(radius);

toWorld = mMitsubaProperty.withNamedData('toWorld', 'transformation');
toWorld.append(mMitsubaProperty.anonymous('rotate', ...
    'x', 1, ...
    'y', -42, ...
    'z', 5.5e6, ...
    'angle', 30));
toWorld.append(mMitsubaProperty.anonymous('scale', ...
    'x', 3, ...
    'y', 9, ...
    'z', -2));
toWorld.append(mMitsubaProperty.anonymous('lookat', ...
    'origin', [0 0 0], ...
    'target', [0 0 -1], ...
    'up', [0 1 0]));
sphere.append(toWorld);

disp(scene.printToFile())
